Global:
  output_num: 10000
  output_dir: StyleText/output_data
  use_gpu: true
  image_height: 32
  image_width: 320
  standard_font: StyleText/fonts/en_standard.ttf
TextDrawer:
  fonts:
    en: StyleText/fonts/en_standard.ttf
    ch: StyleText/fonts/ch_standard.ttf
    ko: StyleText/fonts/ko_standard.ttf
StyleSampler:
  method: DatasetSampler
  image_home: /home/zhaohj/Documents/dataset/rec
  label_file: /home/zhaohj/Documents/dataset/rec/label.txt
  with_label: false
CorpusGenerator:
  method: FileCorpus
  language: ch
  corpus_file: StyleText/medical.txt
Predictor:
  method: StyleTextRecPredictor
  algorithm: StyleTextRec
  scale: 0.00392156862745098
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
  expand_result: false
  bg_generator:
    pretrain: /home/zhaohj/Documents/checkpoint/paddOCR/StyleText/style_text_models/bg_generator
    module_name: bg_generator
    generator_type: BgGeneratorWithMask
    encode_dim: 64
    norm_layer: null
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
    output_factor: 1.05
  text_generator:
    pretrain: /home/zhaohj/Documents/checkpoint/paddOCR/StyleText/style_text_models/text_generator
    module_name: text_generator
    generator_type: TextGenerator
    encode_dim: 64
    norm_layer: InstanceNorm2D
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
  fusion_generator:
    pretrain: /home/zhaohj/Documents/checkpoint/paddOCR/StyleText/style_text_models/fusion_generator
    module_name: fusion_generator
    generator_type: FusionGeneratorSimple
    encode_dim: 64
    norm_layer: null
    conv_block_num: 4
    conv_block_dropout: false
    conv_block_dilation: true
Writer:
  method: SimpleWriter
